name: Check Markdown links

on:
  workflow_dispatch

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
        folder-path: '_posts, _pages'
